Rus translation browse
uniyar-od/dspace-angular pull request #3
Opened 2022-04-20 11:47 UTC by Mamedzuka

## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #[issue-number]
* Requires DSpace/DSpace#[pr-number] (if a REST API PR is required to test this)

## Description
Short summary of changes (1-2 sentences).

## Instructions for Reviewers
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted list of changes in your PR is helpful to reviewers.

List of changes in this PR:
* First, ...
* Second, ...

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ ] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ ] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [ ] My PR doesn't introduce circular dependencies
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

2022-04-20 12:24 UTC, apalkoff requested changes
Надо поправить

2022-04-20 12:24 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  "browse.comcol.by.dateissued": "По Дате Выпуска",
Эээ..в русском языке в заглавиях только первая буква заглавная. Остальные строчные.
```suggestion
  "browse.comcol.by.dateissued": "По дате выпуска",
```

2022-04-20 12:24 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  "browse.comcol.by.rodept": "По Организации",
```suggestion
  "browse.comcol.by.rodept": "По подразделению",
```

2022-04-20 12:24 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  "browse.comcol.by.rpdept": "По Организации",
```suggestion
  "browse.comcol.by.rpdept": "По подразделению",
```

2022-04-20 12:24 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  "browse.comcol.by.subject": "По Дисциплине",
думаю тут имеется в виду «по теме» или «по тематике»
```suggestion
  "browse.comcol.by.subject": "По Дисциплине",
```

2022-04-20 12:24 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  "browse.comcol.head": "Поиск",
Мне не нравится, может «Посмотреть»

```suggestion
  "browse.comcol.head": "Посмотреть",
```

2022-04-20 12:24 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  "browse.empty": "Данных по запросу не найдено.",
```suggestion
  "browse.empty": "Ничего не найдено.",
```

2022-04-20 12:24 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  "browse.metadata.rodept": "Организация",
```suggestion
  "browse.metadata.rodept": "Подразделение",
```

2022-04-20 12:24 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  "browse.metadata.rpdept": "Организация",
```suggestion
  "browse.metadata.rpdept": "Подразделение",
```

2022-04-20 12:24 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  // необходимо понять, что за pjtitle и eqtitle
вероятно pj — printed journal

2022-04-20 12:24 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  // Почему в скобках?
узнаем потом

2022-04-20 12:24 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  // Почему в скобках?
возможно это надписи для пустых полей при заполнении. ну знаешь такие серенькие бывают.

2022-04-20 12:24 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  "browse.startsWith.type_date": "Или введите дату (год-месяц) и нажмите 'Поиск'",
а может всё же и поиск

2022-04-20 13:24 UTC, Mamedzuka commented
ну, я поменял, теперь буду по-русски писать - 1 заглавная буква
надо будет челам, которые работать тоже будут, про общий интерфейс написать
(ну про 1 заглавную букву, про ты-вы и прочая)

2022-04-20 19:31 UTC, apalkoff approved these changes
ok

2022-04-20 20:29 UTC, Mamedzuka commented
а чо Merge сделан или потом делать будем?

2022-04-21 07:07 UTC, apalkoff approved these changes
ok

2022-04-21 12:19 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  "browse.comcol.by.subject": "По Дисциплине",
ну так что же?

2022-04-25 08:40 UTC, apalkoff reviewed
ну чего с этим делать? вливать?

2022-04-25 08:46 UTC, Mamedzuka commented
этот давно мерджить надо

2022-04-26 13:40 UTC, merged