Rus translation collection
uniyar-od/dspace-angular pull request #4
Opened 2022-04-20 13:45 UTC by Mamedzuka

## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #[issue-number]
* Requires DSpace/DSpace#[pr-number] (if a REST API PR is required to test this)

## Description
Short summary of changes (1-2 sentences).

## Instructions for Reviewers
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted list of changes in your PR is helpful to reviewers.

List of changes in this PR:
* First, ...
* Second, ...

**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [ ] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ ] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [ ] My PR doesn't introduce circular dependencies
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

2022-04-21 12:17 UTC, apalkoff requested changes
требуются доработки

2022-04-21 12:17 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  "collection.edit.tabs.curate.head": "Куратор",
Это глагол же
```suggestion
  "collection.edit.tabs.curate.head": "Курировать",
```

2022-04-21 12:17 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  "collection.edit.tabs.source.external": "Данная коллекция включает в себя контент из внешних источников",
получает, а не включает

2022-04-21 12:17 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  "collection.edit.tabs.source.form.errors.oaiSource.required": "Вы должны указать set id набора выбранной коллекции.",
```suggestion
  "collection.edit.tabs.source.form.errors.oaiSource.required": "Требуется указать идентификатор набора (set id) выбранной коллекции.",
```

2022-04-21 12:17 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  "collection.edit.tabs.source.form.recordValidationEnabled": "Проверка записи",
может оставить «валидация»?

2022-04-21 12:17 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  "collection.edit.tabs.source.head": "Источник Контента",
```suggestion
  "collection.edit.tabs.source.head": "Источник контента",
```

2022-04-21 12:17 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  "collection.edit.tabs.source.notifications.discarded.content": "Вносимые изменения были отклонены. Для их восстановления нажмите кнопку 'Отменить'",
Низкопоклонство перед английскими кавычками!

```suggestion
  "collection.edit.tabs.source.notifications.discarded.content": "Вносимые изменения были отклонены. Для их восстановления нажмите кнопку «Отменить»",
```

2022-04-21 12:17 UTC, apalkoff commented on src/assets/i18n/ru.json5
>    "collection.edit.tabs.source.notifications.discarded.title": "Changed discarded",
```suggestion
  "collection.edit.tabs.source.notifications.discarded.title": "Изменения отменены",
```

2022-04-21 12:17 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  "collection.edit.tabs.source.notifications.invalid.title": "Недействительные метаданные",
```suggestion
  "collection.edit.tabs.source.notifications.invalid.title": "Неправильные метаданные",
```

2022-04-21 12:17 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  "collection.edit.tabs.source.notifications.saved.content": "Вносимые в источник контента данной коллекции изменения были сохранены.",
```suggestion
  "collection.edit.tabs.source.notifications.saved.content": "Изменения в источник контента коллекции были сохранены.",
```

2022-04-21 12:17 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  "collection.form.entityType": "Тип юр. лица",
Ой бля
```suggestion
  "collection.form.entityType": "Тип сущности",
```

2022-04-21 12:17 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  "collection.form.errors.entityType.required": "Выберите тип юридического лица для данной коллекции",
```suggestion
  "collection.form.errors.entityType.required": "Выберите тип сущности для коллекции",
```

2022-04-21 12:17 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  "collection.form.rights": "Авторские права (HTML)",
```suggestion
  "collection.form.rights": "Текст авторских права (HTML)",
```

2022-04-21 12:17 UTC, apalkoff commented on src/assets/i18n/ru.json5
> +  "collection.form.description": "Введение (HTML)",
```suggestion
  "collection.form.description": "Вводный текст (HTML)",
```

2022-04-21 13:06 UTC, Mamedzuka commented on src/assets/i18n/ru.json5
> +  "collection.edit.tabs.source.form.recordValidationEnabled": "Проверка записи",
ок

2022-04-21 13:06 UTC, Mamedzuka commented on src/assets/i18n/ru.json5
> +  "collection.edit.tabs.source.notifications.discarded.content": "Вносимые изменения были отклонены. Для их восстановления нажмите кнопку 'Отменить'",
нормальные кавычки 
а треугольнички русские - бяка

2022-04-25 08:40 UTC, apalkoff reviewed
ку ку

2022-04-25 08:42 UTC, Mamedzuka commented
нене
чиллим

2022-04-26 13:28 UTC, Mamedzuka commented
Можно проверять

2022-04-26 15:34 UTC, apalkoff approved these changes

2022-04-26 15:34 UTC, merged